### ISSUE TITLE
Aliases added by module are not supported. 

### ISSUE THREAD

**Issue by mercs600** [nuxt/vite#55]
Thank you for this module and opportunity to use vite in our daily projects. 
I noticed one issue: Aliases added by module are not supported. 

### Versions

nuxt-vite: nuxt-vite@0.0.18
nuxt: nuxt@2.15.2

### Reproduction

Reproduction repository:
module: https://github.com/mercs600/nuxt-vite-module-aliases/tree/master/modules/aliasModule
import: https://github.com/mercs600/nuxt-vite-module-aliases/blob/master/pages/index.vue#L11 

### Description
When I want to extend application aliases by my module - then I get errors:
```bash
 ERROR  [vite]: Rollup failed to resolve import "~aliasModule/moduleComponent" from "pages/index.vue".                                                 16:07:09
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

Module function:
```js
export default function (moduleOptions) {
  this.extendBuild((config, { isDev, isClient }) => {
    config.resolve.alias['~aliasModule'] = resolve(__dirname)
  })
}
```

When I added alias to nuxt.config then it works. 
https://github.com/mercs600/nuxt-vite-module-aliases/blob/master/nuxt.config.js#L38

**Comment by pi0** [comment]
Hi @mercs600. `extendBuild` is used to extend webpack configuration. You have to use [alias] config:

```js
nuxt.options.alias['~aliasModule'] = resolve(__dirname)
```

Two more notes:
- I would recommend using original module name for alias and not starting it `~` since vite has strange behavior with such aliases when used in `node_modules`
- If your code needs transpilation, you need to also push __dirname to `options.build.transpile` to ensure production build has browser compatility

**Comment by mercs600** [comment]
Thank you @pi0, it makes sense 👍
