### ISSUE TITLE
Hola 👋

### ISSUE THREAD

**Issue by Saravia83c** [nuxt/vite#74]
### Versions

nuxt-vite: 
nuxt:

**Comment by Ebiabi** [comment]
YeahDikirim dari Ponsel Huawei saya-------- Pesan Asli --------Subjek: [nuxt/vite] Hola 👋 (#74)Dari: Saravia83c Kepada: nuxt/vite CC: Subscribed 

Versions
nuxt-vite: 
nuxt: 
Reproduction

Description


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nuxt/vite/issues/74",
"url": "https://github.com/nuxt/vite/issues/74",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
